#!/usr/bin/env bash

echo "+------------------------+"
echo "| Discord Install Script |"
echo "+------------------------+"

version=$(jq -r '.version' /opt/discord/resources/build_info.json)

echo $version

echo ""
echo "${version%.*}.$((${version##*.} + 1))"
echo ""

cd ~/Downloads

curl https://stable.dl2.discordapp.net/apps/linux/0.0.135/discord-0.0.$version.tar.gz --output discord.tar.gz

tar -xzvf discord.tar.gz

rm -rf discord.tar.gz

echo "+------------------------------+"
echo "| Discord should be Installed! |"
echo "| Have a nice Chat!            |"
echo "+------------------------------+"

exit 1
